name: on issues
on:
  issues:
    types: [opened, closed]

jobs:

  create_issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:

      - name: Send Telegram message on issue creation via curl
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID_ISSUES }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_STATE: ${{ github.event.issue.state }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          REPOSITORY: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d message_thread_id="${TELEGRAM_THREAD_ID}" \
          -d parse_mode="Markdown" \
          -d text="*${ACTOR} created an issue*
      
          *Title*: \`${ISSUE_TITLE}\`
      
          *Status*: ${ISSUE_STATE}
      
          *Assignees*: ${ISSUE_ASSIGNEES}
      
          *Labels*: ${ISSUE_LABELS}
      
          *Repository*: \`${REPOSITORY}\`
      
          [View Issue](https://github.com/${REPOSITORY}/issues/${ISSUE_NUMBER})"
      

  close_issue:
    name: Close Issue
    runs-on: ubuntu-latest
    steps:
  
      - name: Send Telegram message on issue close via curl
        if: github.event_name == 'issues' && github.event.action == 'closed'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID_ISSUES }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_STATE: ${{ github.event.issue.state }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          REPOSITORY: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d message_thread_id="${TELEGRAM_THREAD_ID}" \
          -d parse_mode="Markdown" \
          -d text="*${ACTOR} closed an issue*
  
          *Title*: \`${ISSUE_TITLE}\`
  
          *Status*: ${ISSUE_STATE}
  
          *Assignees*: ${ISSUE_ASSIGNEES}
  
          *Labels*: ${ISSUE_LABELS}
  
          *Repository*: \`${REPOSITORY}\`
  
          [View Issue](https://github.com/${REPOSITORY}/issues/${ISSUE_NUMBER})"
  

